/******************************************************************
 * COPYRIGHT (c) 2000 Denali Software, Inc.  All rights reserved. *
 * -------------------------------------------------------------- *
 * This code is proprietary and confidential information of       *
 * Denali Software. It may not be reproduced, used or transmitted *
 * in any form whatsoever without the express and written         *
 * permission of Denali Software.                                 *
 ******************************************************************
 * WARNING:  This file was automatically generated.  Manual
 * editing may result in undetermined behavior, and may be in
 * violation of the Denali Support Agreement.
 *****************************************************************/
 /* REL: siemens.munich-DNC_071708 */

#define ACTIVE_AGING_ADDR              0                    
#define ACTIVE_AGING_OFFSET            0                    
#define ACTIVE_AGING_WIDTH             1                    
#define ADDR_CMP_EN_ADDR               0                    
#define ADDR_CMP_EN_OFFSET             8                    
#define ADDR_CMP_EN_WIDTH              1                    
#define ADDR_PINS_ADDR                 13                   
#define ADDR_PINS_OFFSET               16                   
#define ADDR_PINS_WIDTH                3                    
#define ADDR_SPACE_ADDR                29                   
#define ADDR_SPACE_OFFSET              0                    
#define ADDR_SPACE_WIDTH               6                    
#define ADDRESS_WIDTH                  16                   
#define AGE_COUNT_ADDR                 18                   
#define AGE_COUNT_OFFSET               16                   
#define AGE_COUNT_WIDTH                4                    
#define AP_ADDR                        0                    
#define AP_OFFSET                      16                   
#define AP_WIDTH                       1                    
#define APREBIT_ADDR                   18                   
#define APREBIT_CS_WIDTH               4                    
#define APREBIT_OFFSET                 24                   
#define APREBIT_WIDTH                  4                    
#define AREFRESH_ADDR                  0                    
#define AREFRESH_OFFSET                24                   
#define AREFRESH_WIDTH                 1                    
#define AUTO_REFRESH_MODE_ADDR         1                    
#define AUTO_REFRESH_MODE_OFFSET       0                    
#define AUTO_REFRESH_MODE_WIDTH        1                    
#define BANK_SPLIT_EN_ADDR             1                    
#define BANK_SPLIT_EN_OFFSET           8                    
#define BANK_SPLIT_EN_WIDTH            1                    
#define BANK_WIDTH                     3                    
#define BIG_ENDIAN_EN_ADDR             1                    
#define BIG_ENDIAN_EN_OFFSET           16                   
#define BIG_ENDIAN_EN_WIDTH            1                    
#define BIST_ADDR_CHECK_ADDR           1                    
#define BIST_ADDR_CHECK_OFFSET         24                   
#define BIST_ADDR_CHECK_WIDTH          1                    
#define BIST_DATA_CHECK_ADDR           2                    
#define BIST_DATA_CHECK_OFFSET         0                    
#define BIST_DATA_CHECK_WIDTH          1                    
#define BIST_DATA_MASK_ADDR            80                   
#define BIST_DATA_MASK_OFFSET          0                    
#define BIST_DATA_MASK_WIDTH           64                   
#define BIST_DONE_WIDTH                1                    
#define BIST_EXP_DATA_ADDR             86                   
#define BIST_EXP_DATA_OFFSET           0                    
#define BIST_EXP_DATA_WIDTH            128                  
#define BIST_FAIL_ADDR_ADDR            70                   
#define BIST_FAIL_ADDR_OFFSET          0                    
#define BIST_FAIL_ADDR_WIDTH           36                   
#define BIST_FAIL_DATA_ADDR            90                   
#define BIST_FAIL_DATA_OFFSET          0                    
#define BIST_FAIL_DATA_WIDTH           128                  
#define BIST_GO_ADDR                   2                    
#define BIST_GO_OFFSET                 8                    
#define BIST_GO_WIDTH                  1                    
#define BIST_NUM_OF_BG_WIDTH           7                    
#define BIST_RD_FIFO_DEPTH_WIDTH       5                    
#define BIST_RESULT_ADDR               11                   
#define BIST_RESULT_OFFSET             16                   
#define BIST_RESULT_WIDTH              2                    
#define BIST_START_ADDRESS_ADDR        72                   
#define BIST_START_ADDRESS_OFFSET      0                    
#define BIST_START_ADDRESS_WIDTH       36                   
#define BIST_WRD_ADDR_WIDTH            36                   
#define BST_LAT_WIDTH                  2                    
#define BSTLEN_WIDTH                   3                    
#define BYPASS_DELAY_WIDTH             7                    
#define BYTE_WIDTH                     4                    
#define CASLAT_ADDR                    14                   
#define CASLAT_LIN_ADDR                19                   
#define CASLAT_LIN_GATE_ADDR           19                   
#define CASLAT_LIN_GATE_OFFSET         8                    
#define CASLAT_LIN_GATE_WIDTH          4                    
#define CASLAT_LIN_OFFSET              0                    
#define CASLAT_LIN_WIDTH               4                    
#define CASLAT_OFFSET                  0                    
#define CASLAT_WIDTH                   3                    
#define CHECK_B_WIDTH                  8                    
#define CHECK_D_WIDTH                  64                   
#define CKE_DELAY_ADDR                 14                   
#define CKE_DELAY_OFFSET               8                    
#define CKE_DELAY_WIDTH                3                    
#define CKE_SHIFT_WIDTH                8                    
#define CMD_DLY_WIDTH                  3                    
#define CMDLAT_REDUC_EN_WIDTH          1                    
#define COLUMN_SIZE_ADDR               14                   
#define COLUMN_SIZE_OFFSET             16                   
#define COLUMN_SIZE_WIDTH              3                    
#define COMMAND_AGE_COUNT_ADDR         19                   
#define COMMAND_AGE_COUNT_OFFSET       16                   
#define COMMAND_AGE_COUNT_WIDTH        4                    
#define CONCURRENTAP_ADDR              2                    
#define CONCURRENTAP_OFFSET            16                   
#define CONCURRENTAP_WIDTH             1                    
#define CONTROL_WORD_WIDTH             14                   
#define CS_BANK_WIDTH                  4                    
#define CS_DIFF_WIDTH                  1                    
#define CS_MAP_ADDR                    19                   
#define CS_MAP_OFFSET                  24                   
#define CS_MAP_WIDTH                   2                    
#define CS_WIDTH                       1                    
#define CTRL_RAW_ADDR                  11                   
#define CTRL_RAW_OFFSET                24                   
#define CTRL_RAW_WIDTH                 2                    
#define CTRL_WIDTH                     2                    
#define DATA_BYTE_WIDTH                4                    
#define DATA_WIDTH                     64                   
#define DDR_MODE_WIDTH                 3                    
#define DECODED_BSTLEN_WIDTH           4                    
#define DENALI0_PORT_ORDERING_ADDR     3                    
#define DENALI0_PORT_ORDERING_OFFSET   0                    
#define DENALI0_PORT_ORDERING_WIDTH    1                    
#define DENALI0_PRIORITY0_RELATIVE_PRIORITY_ADDR 20                   
#define DENALI0_PRIORITY0_RELATIVE_PRIORITY_OFFSET 0                    
#define DENALI0_PRIORITY0_RELATIVE_PRIORITY_WIDTH 4                    
#define DENALI0_PRIORITY1_RELATIVE_PRIORITY_ADDR 20                   
#define DENALI0_PRIORITY1_RELATIVE_PRIORITY_OFFSET 8                    
#define DENALI0_PRIORITY1_RELATIVE_PRIORITY_WIDTH 4                    
#define DENALI0_PRIORITY2_RELATIVE_PRIORITY_ADDR 20                   
#define DENALI0_PRIORITY2_RELATIVE_PRIORITY_OFFSET 16                   
#define DENALI0_PRIORITY2_RELATIVE_PRIORITY_WIDTH 4                    
#define DENALI0_PRIORITY3_RELATIVE_PRIORITY_ADDR 20                   
#define DENALI0_PRIORITY3_RELATIVE_PRIORITY_OFFSET 24                   
#define DENALI0_PRIORITY3_RELATIVE_PRIORITY_WIDTH 4                    
#define DENALI0_PRIORITY_RELAX_ADDR    31                   
#define DENALI0_PRIORITY_RELAX_OFFSET  0                    
#define DENALI0_PRIORITY_RELAX_WIDTH   10                   
#define DENALI1_PORT_ORDERING_ADDR     3                    
#define DENALI1_PORT_ORDERING_OFFSET   8                    
#define DENALI1_PORT_ORDERING_WIDTH    1                    
#define DENALI1_PRIORITY0_RELATIVE_PRIORITY_ADDR 21                   
#define DENALI1_PRIORITY0_RELATIVE_PRIORITY_OFFSET 0                    
#define DENALI1_PRIORITY0_RELATIVE_PRIORITY_WIDTH 4                    
#define DENALI1_PRIORITY1_RELATIVE_PRIORITY_ADDR 21                   
#define DENALI1_PRIORITY1_RELATIVE_PRIORITY_OFFSET 8                    
#define DENALI1_PRIORITY1_RELATIVE_PRIORITY_WIDTH 4                    
#define DENALI1_PRIORITY2_RELATIVE_PRIORITY_ADDR 21                   
#define DENALI1_PRIORITY2_RELATIVE_PRIORITY_OFFSET 16                   
#define DENALI1_PRIORITY2_RELATIVE_PRIORITY_WIDTH 4                    
#define DENALI1_PRIORITY3_RELATIVE_PRIORITY_ADDR 21                   
#define DENALI1_PRIORITY3_RELATIVE_PRIORITY_OFFSET 24                   
#define DENALI1_PRIORITY3_RELATIVE_PRIORITY_WIDTH 4                    
#define DENALI1_PRIORITY_RELAX_ADDR    31                   
#define DENALI1_PRIORITY_RELAX_OFFSET  16                   
#define DENALI1_PRIORITY_RELAX_WIDTH   10                   
#define DFI_CTLR_DATA_WIDTH            144                  
#define DFI_CTLR_WRDATA_MASK_WIDTH     18                   
#define DFI_DATA_BYTE_WIDTH            9                    
#define DFI_DATA_WIDTH                 144                  
#define DFI_WRDATA_MASK_WIDTH          18                   
#define DFT_CTRL_REG_ADDR              47                   
#define DFT_CTRL_REG_OFFSET            0                    
#define DFT_CTRL_REG_WIDTH             32                   
#define DLL_BYPASS_MODE_ADDR           3                    
#define DLL_BYPASS_MODE_OFFSET         24                   
#define DLL_BYPASS_MODE_WIDTH          1                    
#define DLL_CTRL_REG_0_0_ADDR          94                   
#define DLL_CTRL_REG_0_0_OFFSET        0                    
#define DLL_CTRL_REG_0_0_WIDTH         32                   
#define DLL_CTRL_REG_0_1_ADDR          95                   
#define DLL_CTRL_REG_0_1_OFFSET        0                    
#define DLL_CTRL_REG_0_1_WIDTH         32                   
#define DLL_CTRL_REG_0_2_ADDR          96                   
#define DLL_CTRL_REG_0_2_OFFSET        0                    
#define DLL_CTRL_REG_0_2_WIDTH         32                   
#define DLL_CTRL_REG_0_3_ADDR          97                   
#define DLL_CTRL_REG_0_3_OFFSET        0                    
#define DLL_CTRL_REG_0_3_WIDTH         32                   
#define DLL_CTRL_REG_0_4_ADDR          98                   
#define DLL_CTRL_REG_0_4_OFFSET        0                    
#define DLL_CTRL_REG_0_4_WIDTH         32                   
#define DLL_CTRL_REG_0_5_ADDR          99                   
#define DLL_CTRL_REG_0_5_OFFSET        0                    
#define DLL_CTRL_REG_0_5_WIDTH         32                   
#define DLL_CTRL_REG_0_6_ADDR          100                  
#define DLL_CTRL_REG_0_6_OFFSET        0                    
#define DLL_CTRL_REG_0_6_WIDTH         32                   
#define DLL_CTRL_REG_0_7_ADDR          101                  
#define DLL_CTRL_REG_0_7_OFFSET        0                    
#define DLL_CTRL_REG_0_7_WIDTH         32                   
#define DLL_CTRL_REG_0_8_ADDR          102                  
#define DLL_CTRL_REG_0_8_OFFSET        0                    
#define DLL_CTRL_REG_0_8_WIDTH         32                   
#define DLL_CTRL_REG_1_0_ADDR          103                  
#define DLL_CTRL_REG_1_0_OFFSET        0                    
#define DLL_CTRL_REG_1_0_WIDTH         32                   
#define DLL_CTRL_REG_1_1_ADDR          104                  
#define DLL_CTRL_REG_1_1_OFFSET        0                    
#define DLL_CTRL_REG_1_1_WIDTH         32                   
#define DLL_CTRL_REG_1_2_ADDR          105                  
#define DLL_CTRL_REG_1_2_OFFSET        0                    
#define DLL_CTRL_REG_1_2_WIDTH         32                   
#define DLL_CTRL_REG_1_3_ADDR          106                  
#define DLL_CTRL_REG_1_3_OFFSET        0                    
#define DLL_CTRL_REG_1_3_WIDTH         32                   
#define DLL_CTRL_REG_1_4_ADDR          107                  
#define DLL_CTRL_REG_1_4_OFFSET        0                    
#define DLL_CTRL_REG_1_4_WIDTH         32                   
#define DLL_CTRL_REG_1_5_ADDR          108                  
#define DLL_CTRL_REG_1_5_OFFSET        0                    
#define DLL_CTRL_REG_1_5_WIDTH         32                   
#define DLL_CTRL_REG_1_6_ADDR          109                  
#define DLL_CTRL_REG_1_6_OFFSET        0                    
#define DLL_CTRL_REG_1_6_WIDTH         32                   
#define DLL_CTRL_REG_1_7_ADDR          110                  
#define DLL_CTRL_REG_1_7_OFFSET        0                    
#define DLL_CTRL_REG_1_7_WIDTH         32                   
#define DLL_CTRL_REG_1_8_ADDR          111                  
#define DLL_CTRL_REG_1_8_OFFSET        0                    
#define DLL_CTRL_REG_1_8_WIDTH         32                   
#define DLL_DQS_DELAY_BYPASS_WIDTH     7                    
#define DLL_DQS_DELAY_WIDTH            7                    
#define DLL_INCREMENT_WIDTH            6                    
#define DLL_LOCK_ADDR                  27                   
#define DLL_LOCK_OFFSET                8                    
#define DLL_LOCK_WIDTH                 6                    
#define DLL_NUM_DELAYS_WIDTH           6                    
#define DLL_OBS_REG_0_0_ADDR           112                  
#define DLL_OBS_REG_0_0_OFFSET         0                    
#define DLL_OBS_REG_0_0_WIDTH          32                   
#define DLL_OBS_REG_0_1_ADDR           113                  
#define DLL_OBS_REG_0_1_OFFSET         0                    
#define DLL_OBS_REG_0_1_WIDTH          32                   
#define DLL_OBS_REG_0_2_ADDR           114                  
#define DLL_OBS_REG_0_2_OFFSET         0                    
#define DLL_OBS_REG_0_2_WIDTH          32                   
#define DLL_OBS_REG_0_3_ADDR           115                  
#define DLL_OBS_REG_0_3_OFFSET         0                    
#define DLL_OBS_REG_0_3_WIDTH          32                   
#define DLL_OBS_REG_0_4_ADDR           116                  
#define DLL_OBS_REG_0_4_OFFSET         0                    
#define DLL_OBS_REG_0_4_WIDTH          32                   
#define DLL_OBS_REG_0_5_ADDR           117                  
#define DLL_OBS_REG_0_5_OFFSET         0                    
#define DLL_OBS_REG_0_5_WIDTH          32                   
#define DLL_OBS_REG_0_6_ADDR           118                  
#define DLL_OBS_REG_0_6_OFFSET         0                    
#define DLL_OBS_REG_0_6_WIDTH          32                   
#define DLL_OBS_REG_0_7_ADDR           119                  
#define DLL_OBS_REG_0_7_OFFSET         0                    
#define DLL_OBS_REG_0_7_WIDTH          32                   
#define DLL_OBS_REG_0_8_ADDR           120                  
#define DLL_OBS_REG_0_8_OFFSET         0                    
#define DLL_OBS_REG_0_8_WIDTH          32                   
#define DLL_OBS_REG_1_0_ADDR           130                  
#define DLL_OBS_REG_1_0_OFFSET         0                    
#define DLL_OBS_REG_1_0_WIDTH          43                   
#define DLL_OBS_REG_1_1_ADDR           132                  
#define DLL_OBS_REG_1_1_OFFSET         0                    
#define DLL_OBS_REG_1_1_WIDTH          43                   
#define DLL_OBS_REG_1_2_ADDR           134                  
#define DLL_OBS_REG_1_2_OFFSET         0                    
#define DLL_OBS_REG_1_2_WIDTH          43                   
#define DLL_OBS_REG_1_3_ADDR           136                  
#define DLL_OBS_REG_1_3_OFFSET         0                    
#define DLL_OBS_REG_1_3_WIDTH          43                   
#define DLL_OBS_REG_1_4_ADDR           138                  
#define DLL_OBS_REG_1_4_OFFSET         0                    
#define DLL_OBS_REG_1_4_WIDTH          43                   
#define DLL_OBS_REG_1_5_ADDR           140                  
#define DLL_OBS_REG_1_5_OFFSET         0                    
#define DLL_OBS_REG_1_5_WIDTH          43                   
#define DLL_OBS_REG_1_6_ADDR           142                  
#define DLL_OBS_REG_1_6_OFFSET         0                    
#define DLL_OBS_REG_1_6_WIDTH          43                   
#define DLL_OBS_REG_1_7_ADDR           144                  
#define DLL_OBS_REG_1_7_OFFSET         0                    
#define DLL_OBS_REG_1_7_WIDTH          43                   
#define DLL_OBS_REG_1_8_ADDR           146                  
#define DLL_OBS_REG_1_8_OFFSET         0                    
#define DLL_OBS_REG_1_8_WIDTH          43                   
#define DLL_OBS_REG_2_0_ADDR           148                  
#define DLL_OBS_REG_2_0_OFFSET         0                    
#define DLL_OBS_REG_2_0_WIDTH          43                   
#define DLL_OBS_REG_2_1_ADDR           150                  
#define DLL_OBS_REG_2_1_OFFSET         0                    
#define DLL_OBS_REG_2_1_WIDTH          43                   
#define DLL_OBS_REG_2_2_ADDR           152                  
#define DLL_OBS_REG_2_2_OFFSET         0                    
#define DLL_OBS_REG_2_2_WIDTH          43                   
#define DLL_OBS_REG_2_3_ADDR           154                  
#define DLL_OBS_REG_2_3_OFFSET         0                    
#define DLL_OBS_REG_2_3_WIDTH          43                   
#define DLL_OBS_REG_2_4_ADDR           156                  
#define DLL_OBS_REG_2_4_OFFSET         0                    
#define DLL_OBS_REG_2_4_WIDTH          43                   
#define DLL_OBS_REG_2_5_ADDR           158                  
#define DLL_OBS_REG_2_5_OFFSET         0                    
#define DLL_OBS_REG_2_5_WIDTH          43                   
#define DLL_OBS_REG_2_6_ADDR           160                  
#define DLL_OBS_REG_2_6_OFFSET         0                    
#define DLL_OBS_REG_2_6_WIDTH          43                   
#define DLL_OBS_REG_2_7_ADDR           162                  
#define DLL_OBS_REG_2_7_OFFSET         0                    
#define DLL_OBS_REG_2_7_WIDTH          43                   
#define DLL_OBS_REG_2_8_ADDR           164                  
#define DLL_OBS_REG_2_8_OFFSET         0                    
#define DLL_OBS_REG_2_8_WIDTH          43                   
#define DLL_OBS_REG_3_0_ADDR           166                  
#define DLL_OBS_REG_3_0_OFFSET         0                    
#define DLL_OBS_REG_3_0_WIDTH          43                   
#define DLL_OBS_REG_3_1_ADDR           168                  
#define DLL_OBS_REG_3_1_OFFSET         0                    
#define DLL_OBS_REG_3_1_WIDTH          43                   
#define DLL_OBS_REG_3_2_ADDR           170                  
#define DLL_OBS_REG_3_2_OFFSET         0                    
#define DLL_OBS_REG_3_2_WIDTH          43                   
#define DLL_OBS_REG_3_3_ADDR           172                  
#define DLL_OBS_REG_3_3_OFFSET         0                    
#define DLL_OBS_REG_3_3_WIDTH          43                   
#define DLL_OBS_REG_3_4_ADDR           174                  
#define DLL_OBS_REG_3_4_OFFSET         0                    
#define DLL_OBS_REG_3_4_WIDTH          43                   
#define DLL_OBS_REG_3_5_ADDR           176                  
#define DLL_OBS_REG_3_5_OFFSET         0                    
#define DLL_OBS_REG_3_5_WIDTH          43                   
#define DLL_OBS_REG_3_6_ADDR           178                  
#define DLL_OBS_REG_3_6_OFFSET         0                    
#define DLL_OBS_REG_3_6_WIDTH          43                   
#define DLL_OBS_REG_3_7_ADDR           180                  
#define DLL_OBS_REG_3_7_OFFSET         0                    
#define DLL_OBS_REG_3_7_WIDTH          43                   
#define DLL_OBS_REG_3_8_ADDR           182                  
#define DLL_OBS_REG_3_8_OFFSET         0                    
#define DLL_OBS_REG_3_8_WIDTH          43                   
#define DLL_RST_ADJ_DLY_ADDR           185                  
#define DLL_RST_ADJ_DLY_OFFSET         0                    
#define DLL_RST_ADJ_DLY_WIDTH          8                    
#define DLL_RST_DELAY_ADDR             185                  
#define DLL_RST_DELAY_OFFSET           16                   
#define DLL_RST_DELAY_WIDTH            16                   
#define DLL_START_POINT_WIDTH          6                    
#define DLLLOCKREG_ADDR                3                    
#define DLLLOCKREG_OFFSET              16                   
#define DLLLOCKREG_WIDTH               1                    
#define DM_WIDTH                       8                    
#define DQS_N_EN_ADDR                  4                    
#define DQS_N_EN_OFFSET                0                    
#define DQS_N_EN_WIDTH                 1                    
#define DQS_WIDTH                      16                   
#define DRAM_CLASS_ADDR                184                  
#define DRAM_CLASS_OFFSET              0                    
#define DRAM_CLASS_WIDTH               4                    
#define DRAM_CLK_DISABLE_ADDR          22                   
#define DRAM_CLK_DISABLE_OFFSET        0                    
#define DRAM_CLK_DISABLE_WIDTH         2                    
#define DRIVE_DQ_DQS_ADDR              4                    
#define DRIVE_DQ_DQS_OFFSET            8                    
#define DRIVE_DQ_DQS_WIDTH             1                    
#define ECC_C_ADDR_ADDR                74                   
#define ECC_C_ADDR_OFFSET              0                    
#define ECC_C_ADDR_WIDTH               36                   
#define ECC_C_DATA_ADDR                82                   
#define ECC_C_DATA_OFFSET              0                    
#define ECC_C_DATA_WIDTH               64                   
#define ECC_C_ID_ADDR                  12                   
#define ECC_C_ID_OFFSET                0                    
#define ECC_C_ID_WIDTH                 2                    
#define ECC_C_SYND_ADDR                29                   
#define ECC_C_SYND_OFFSET              16                   
#define ECC_C_SYND_WIDTH               8                    
#define ECC_CHECK_WIDTH                8                    
#define ECC_DATA_WIDTH                 64                   
#define ECC_DISABLE_W_UC_ERR_ADDR      4                    
#define ECC_DISABLE_W_UC_ERR_OFFSET    16                   
#define ECC_DISABLE_W_UC_ERR_WIDTH     1                    
#define ECC_DM_WIDTH                   1                    
#define ECC_DQS_WIDTH                  2                    
#define ECC_U_ADDR_ADDR                76                   
#define ECC_U_ADDR_OFFSET              0                    
#define ECC_U_ADDR_WIDTH               36                   
#define ECC_U_DATA_ADDR                84                   
#define ECC_U_DATA_OFFSET              0                    
#define ECC_U_DATA_WIDTH               64                   
#define ECC_U_ID_ADDR                  12                   
#define ECC_U_ID_OFFSET                8                    
#define ECC_U_ID_WIDTH                 2                    
#define ECC_U_SYND_ADDR                29                   
#define ECC_U_SYND_OFFSET              24                   
#define ECC_U_SYND_WIDTH               8                    
#define EFFECT_USER_DATA_WIDTH         128                  
#define EIGHT_BANK_MODE_ADDR           4                    
#define EIGHT_BANK_MODE_OFFSET         24                   
#define EIGHT_BANK_MODE_WIDTH          1                    
#define EMRS1_DATA_0_ADDR              186                  
#define EMRS1_DATA_0_OFFSET            0                    
#define EMRS1_DATA_0_WIDTH             16                   
#define EMRS1_DATA_1_ADDR              186                  
#define EMRS1_DATA_1_OFFSET            16                   
#define EMRS1_DATA_1_WIDTH             16                   
#define EMRS1_DATA_WIDTH               16                   
#define EMRS2_DATA_0_ADDR              41                   
#define EMRS2_DATA_0_OFFSET            0                    
#define EMRS2_DATA_0_WIDTH             16                   
#define EMRS2_DATA_1_ADDR              42                   
#define EMRS2_DATA_1_OFFSET            0                    
#define EMRS2_DATA_1_WIDTH             16                   
#define EMRS2_DATA_WIDTH               16                   
#define EMRS3_DATA_0_ADDR              187                  
#define EMRS3_DATA_0_OFFSET            0                    
#define EMRS3_DATA_0_WIDTH             16                   
#define EMRS3_DATA_1_ADDR              187                  
#define EMRS3_DATA_1_OFFSET            16                   
#define EMRS3_DATA_1_WIDTH             16                   
#define EMRS3_DATA_WIDTH               16                   
#define EMRS_DATA_WIDTH                16                   
#define ENABLE_QUICK_SREFRESH_ADDR     5                    
#define ENABLE_QUICK_SREFRESH_OFFSET   0                    
#define ENABLE_QUICK_SREFRESH_WIDTH    1                    
#define FAST_WRITE_ADDR                5                    
#define FAST_WRITE_OFFSET              8                    
#define FAST_WRITE_WIDTH               1                    
#define FWC_ADDR                       5                    
#define FWC_OFFSET                     16                   
#define FWC_WIDTH                      1                    
#define INHIBIT_CMD_WIDTH              11                   
#define INITAREF_ADDR                  22                   
#define INITAREF_OFFSET                8                    
#define INITAREF_WIDTH                 4                    
#define INT_ACK_ADDR                   32                   
#define INT_ACK_OFFSET                 0                    
#define INT_ACK_WIDTH                  12                   
#define INT_MASK_ADDR                  32                   
#define INT_MASK_OFFSET                16                   
#define INT_MASK_WIDTH                 13                   
#define INT_STATUS_ADDR                33                   
#define INT_STATUS_OFFSET              0                    
#define INT_STATUS_WIDTH               13                   
#define INTRPTAPBURST_ADDR             5                    
#define INTRPTAPBURST_OFFSET           24                   
#define INTRPTAPBURST_WIDTH            1                    
#define INTRPTREADA_ADDR               6                    
#define INTRPTREADA_OFFSET             0                    
#define INTRPTREADA_WIDTH              1                    
#define INTRPTWRITEA_ADDR              6                    
#define INTRPTWRITEA_OFFSET            8                    
#define INTRPTWRITEA_WIDTH             1                    
#define MAX_ADDR_WIDTH                 36                   
#define MAX_CMD_REG_WIDTH              78                   
#define MAX_CMD_WIDTH                  3                    
#define MAX_COL_REG_ADDR               22                   
#define MAX_COL_REG_OFFSET             16                   
#define MAX_COL_REG_WIDTH              4                    
#define MAX_CS_REG_ADDR                14                   
#define MAX_CS_REG_OFFSET              24                   
#define MAX_CS_REG_WIDTH               2                    
#define MAX_LEN_WIDTH                  7                    
#define MAX_LEN_WORD_WIDTH             4                    
#define MAX_REG_ADDR                   191                  
#define MAX_ROW_REG_ADDR               27                   
#define MAX_ROW_REG_OFFSET             16                   
#define MAX_ROW_REG_WIDTH              5                    
#define MAX_USER_ADDR_WIDTH            36                   
#define MDQS_MULT_ADDR                 12                   
#define MDQS_MULT_OFFSET               16                   
#define MDQS_MULT_WIDTH                2                    
#define MEM_DATA_WIDTH                 64                   
#define MEM_DM_WIDTH                   8                    
#define MEM_DQS_WIDTH                  16                   
#define MEM_ECC_CHECK_WIDTH            8                    
#define MEM_ECC_DM_WIDTH               1                    
#define MEM_ECC_DQS_WIDTH              2                    
#define MRS_DATA_0_ADDR                188                  
#define MRS_DATA_0_OFFSET              0                    
#define MRS_DATA_0_WIDTH               16                   
#define MRS_DATA_1_ADDR                188                  
#define MRS_DATA_1_OFFSET              16                   
#define MRS_DATA_1_WIDTH               16                   
#define MRS_DATA_WIDTH                 16                   
#define NO_CMD_INIT_ADDR               6                    
#define NO_CMD_INIT_OFFSET             16                   
#define NO_CMD_INIT_WIDTH              1                    
#define NON_INHIBIT_CMD_WIDTH          4                    
#define OCD_ADJUST_PDN_CS_0_ADDR       27                   
#define OCD_ADJUST_PDN_CS_0_OFFSET     24                   
#define OCD_ADJUST_PDN_CS_0_WIDTH      5                    
#define OCD_ADJUST_PUP_CS_0_ADDR       28                   
#define OCD_ADJUST_PUP_CS_0_OFFSET     0                    
#define OCD_ADJUST_PUP_CS_0_WIDTH      5                    
#define ODT_ADD_TURN_CLK_EN_ADDR       6                    
#define ODT_ADD_TURN_CLK_EN_OFFSET     24                   
#define ODT_ADD_TURN_CLK_EN_WIDTH      1                    
#define ODT_ALT_EN_ADDR                7                    
#define ODT_ALT_EN_OFFSET              0                    
#define ODT_ALT_EN_WIDTH               1                    
#define ODT_DELAY_WIDTH                2                    
#define ODT_RD_MAP_CS0_ADDR            22                   
#define ODT_RD_MAP_CS0_OFFSET          24                   
#define ODT_RD_MAP_CS0_WIDTH           2                    
#define ODT_RD_MAP_CS1_ADDR            23                   
#define ODT_RD_MAP_CS1_OFFSET          0                    
#define ODT_RD_MAP_CS1_WIDTH           2                    
#define ODT_WR_MAP_CS0_ADDR            23                   
#define ODT_WR_MAP_CS0_OFFSET          24                   
#define ODT_WR_MAP_CS0_WIDTH           2                    
#define ODT_WR_MAP_CS1_ADDR            24                   
#define ODT_WR_MAP_CS1_OFFSET          0                    
#define ODT_WR_MAP_CS1_WIDTH           2                    
#define OUT_OF_RANGE_ADDR_ADDR         78                   
#define OUT_OF_RANGE_ADDR_OFFSET       0                    
#define OUT_OF_RANGE_ADDR_WIDTH        36                   
#define OUT_OF_RANGE_LENGTH_ADDR       29                   
#define OUT_OF_RANGE_LENGTH_OFFSET     8                    
#define OUT_OF_RANGE_LENGTH_WIDTH      7                    
#define OUT_OF_RANGE_SOURCE_ID_ADDR    12                   
#define OUT_OF_RANGE_SOURCE_ID_OFFSET  24                   
#define OUT_OF_RANGE_SOURCE_ID_WIDTH   2                    
#define OUT_OF_RANGE_TYPE_ADDR         15                   
#define OUT_OF_RANGE_TYPE_OFFSET       0                    
#define OUT_OF_RANGE_TYPE_WIDTH        3                    
#define PAD_CTRL_REG_0_ADDR            48                   
#define PAD_CTRL_REG_0_OFFSET          0                    
#define PAD_CTRL_REG_0_WIDTH           32                   
#define PAGE_WIDTH                     20                   
#define PHY_CTRL_REG_0_0_ADDR          49                   
#define PHY_CTRL_REG_0_0_OFFSET        0                    
#define PHY_CTRL_REG_0_0_WIDTH         32                   
#define PHY_CTRL_REG_0_1_ADDR          50                   
#define PHY_CTRL_REG_0_1_OFFSET        0                    
#define PHY_CTRL_REG_0_1_WIDTH         32                   
#define PHY_CTRL_REG_0_2_ADDR          51                   
#define PHY_CTRL_REG_0_2_OFFSET        0                    
#define PHY_CTRL_REG_0_2_WIDTH         32                   
#define PHY_CTRL_REG_0_3_ADDR          52                   
#define PHY_CTRL_REG_0_3_OFFSET        0                    
#define PHY_CTRL_REG_0_3_WIDTH         32                   
#define PHY_CTRL_REG_0_4_ADDR          53                   
#define PHY_CTRL_REG_0_4_OFFSET        0                    
#define PHY_CTRL_REG_0_4_WIDTH         32                   
#define PHY_CTRL_REG_0_5_ADDR          54                   
#define PHY_CTRL_REG_0_5_OFFSET        0                    
#define PHY_CTRL_REG_0_5_WIDTH         32                   
#define PHY_CTRL_REG_0_6_ADDR          55                   
#define PHY_CTRL_REG_0_6_OFFSET        0                    
#define PHY_CTRL_REG_0_6_WIDTH         32                   
#define PHY_CTRL_REG_0_7_ADDR          56                   
#define PHY_CTRL_REG_0_7_OFFSET        0                    
#define PHY_CTRL_REG_0_7_WIDTH         32                   
#define PHY_CTRL_REG_0_8_ADDR          57                   
#define PHY_CTRL_REG_0_8_OFFSET        0                    
#define PHY_CTRL_REG_0_8_WIDTH         32                   
#define PHY_CTRL_REG_1_0_ADDR          59                   
#define PHY_CTRL_REG_1_0_OFFSET        0                    
#define PHY_CTRL_REG_1_0_WIDTH         32                   
#define PHY_CTRL_REG_1_1_ADDR          60                   
#define PHY_CTRL_REG_1_1_OFFSET        0                    
#define PHY_CTRL_REG_1_1_WIDTH         32                   
#define PHY_CTRL_REG_1_2_ADDR          61                   
#define PHY_CTRL_REG_1_2_OFFSET        0                    
#define PHY_CTRL_REG_1_2_WIDTH         32                   
#define PHY_CTRL_REG_1_3_ADDR          62                   
#define PHY_CTRL_REG_1_3_OFFSET        0                    
#define PHY_CTRL_REG_1_3_WIDTH         32                   
#define PHY_CTRL_REG_1_4_ADDR          63                   
#define PHY_CTRL_REG_1_4_OFFSET        0                    
#define PHY_CTRL_REG_1_4_WIDTH         32                   
#define PHY_CTRL_REG_1_5_ADDR          64                   
#define PHY_CTRL_REG_1_5_OFFSET        0                    
#define PHY_CTRL_REG_1_5_WIDTH         32                   
#define PHY_CTRL_REG_1_6_ADDR          65                   
#define PHY_CTRL_REG_1_6_OFFSET        0                    
#define PHY_CTRL_REG_1_6_WIDTH         32                   
#define PHY_CTRL_REG_1_7_ADDR          66                   
#define PHY_CTRL_REG_1_7_OFFSET        0                    
#define PHY_CTRL_REG_1_7_WIDTH         32                   
#define PHY_CTRL_REG_1_8_ADDR          67                   
#define PHY_CTRL_REG_1_8_OFFSET        0                    
#define PHY_CTRL_REG_1_8_WIDTH         32                   
#define PHY_CTRL_REG_2_ADDR            69                   
#define PHY_CTRL_REG_2_OFFSET          0                    
#define PHY_CTRL_REG_2_WIDTH           32                   
#define PHY_OBS_REG_0_0_ADDR           121                  
#define PHY_OBS_REG_0_0_OFFSET         0                    
#define PHY_OBS_REG_0_0_WIDTH          32                   
#define PHY_OBS_REG_0_1_ADDR           122                  
#define PHY_OBS_REG_0_1_OFFSET         0                    
#define PHY_OBS_REG_0_1_WIDTH          32                   
#define PHY_OBS_REG_0_2_ADDR           123                  
#define PHY_OBS_REG_0_2_OFFSET         0                    
#define PHY_OBS_REG_0_2_WIDTH          32                   
#define PHY_OBS_REG_0_3_ADDR           124                  
#define PHY_OBS_REG_0_3_OFFSET         0                    
#define PHY_OBS_REG_0_3_WIDTH          32                   
#define PHY_OBS_REG_0_4_ADDR           125                  
#define PHY_OBS_REG_0_4_OFFSET         0                    
#define PHY_OBS_REG_0_4_WIDTH          32                   
#define PHY_OBS_REG_0_5_ADDR           126                  
#define PHY_OBS_REG_0_5_OFFSET         0                    
#define PHY_OBS_REG_0_5_WIDTH          32                   
#define PHY_OBS_REG_0_6_ADDR           127                  
#define PHY_OBS_REG_0_6_OFFSET         0                    
#define PHY_OBS_REG_0_6_WIDTH          32                   
#define PHY_OBS_REG_0_7_ADDR           128                  
#define PHY_OBS_REG_0_7_OFFSET         0                    
#define PHY_OBS_REG_0_7_WIDTH          32                   
#define PHY_OBS_REG_0_8_ADDR           129                  
#define PHY_OBS_REG_0_8_OFFSET         0                    
#define PHY_OBS_REG_0_8_WIDTH          32                   
#define PHY_OBS_REG_0_WIDTH            32                   
#define PLACEMENT_EN_ADDR              7                    
#define PLACEMENT_EN_OFFSET            8                    
#define PLACEMENT_EN_WIDTH             1                    
#define PORT0_DATA_WIDTH               128                  
#define PORT0_MASK_WIDTH               16                   
#define PORT1_DATA_WIDTH               128                  
#define PORT1_MASK_WIDTH               16                   
#define PORT_ORDERING_WIDTH            1                    
#define PORT_WIDTH                     1                    
#define POWER_DOWN_ADDR                7                    
#define POWER_DOWN_OFFSET              16                   
#define POWER_DOWN_WIDTH               1                    
#define PRIORITY_EN_ADDR               7                    
#define PRIORITY_EN_OFFSET             24                   
#define PRIORITY_EN_WIDTH              1                    
#define PRIORITY_RELAX_WIDTH           10                   
#define PWRUP_SREFRESH_EXIT_ADDR       8                    
#define PWRUP_SREFRESH_EXIT_OFFSET     0                    
#define PWRUP_SREFRESH_EXIT_WIDTH      1                    
#define Q_FULLNESS_ADDR                15                   
#define Q_FULLNESS_OFFSET              8                    
#define Q_FULLNESS_WIDTH               3                    
#define RDDATA_INFO_FIFO_WIDTH         44                   
#define RDLAT_ADJ_ADDR                 184                  
#define RDLAT_ADJ_OFFSET               8                    
#define RDLAT_ADJ_WIDTH                4                    
#define RDLAT_WIDTH                    4                    
#define READ_FIFO_DEPTH_WIDTH          0                    
#define READFIFO_DATA_WIDTH            130                  
#define REDUC_ADDR                     8                    
#define REDUC_OFFSET                   8                    
#define REDUC_WIDTH                    1                    
#define REG_ADDR_WIDTH                 8                    
#define REG_DATA_WIDTH                 32                   
#define REG_DIMM_ENABLE_ADDR           8                    
#define REG_DIMM_ENABLE_OFFSET         16                   
#define REG_DIMM_ENABLE_WIDTH          1                    
#define REG_MASK_WIDTH                 4                    
#define RELATIVE_PRIORITY_WIDTH        4                    
#define RMODW_FIFO_DEPTH_WIDTH         3                    
#define RMODW_WIDTH                    3                    
#define RTT_0_ADDR                     13                   
#define RTT_0_OFFSET                   0                    
#define RTT_0_WIDTH                    2                    
#define RTT_PAD_TERMINATION_WIDTH      2                    
#define RW_SAME_EN_ADDR                8                    
#define RW_SAME_EN_OFFSET              24                   
#define RW_SAME_EN_WIDTH               1                    
#define SPLIT_STATE_WIDTH              3                    
#define SREFRESH_ADDR                  9                    
#define SREFRESH_OFFSET                0                    
#define SREFRESH_WIDTH                 1                    
#define START_ADDR                     9                    
#define START_OFFSET                   8                    
#define START_WIDTH                    1                    
#define STAT_WIDTH                     2                    
#define SWAP_EN_ADDR                   9                    
#define SWAP_EN_OFFSET                 16                   
#define SWAP_EN_WIDTH                  1                    
#define SWAP_PORT_RW_SAME_EN_ADDR      9                    
#define SWAP_PORT_RW_SAME_EN_OFFSET    24                   
#define SWAP_PORT_RW_SAME_EN_WIDTH     1                    
#define TCKE_ADDR                      16                   
#define TCKE_OFFSET                    16                   
#define TCKE_WIDTH                     3                    
#define TCPD_ADDR                      35                   
#define TCPD_OFFSET                    16                   
#define TCPD_WIDTH                     16                   
#define TDAL_ADDR                      25                   
#define TDAL_OFFSET                    0                    
#define TDAL_WIDTH                     5                    
#define TDFI_CTRLUPD_MAX_ADDR          33                   
#define TDFI_CTRLUPD_MAX_OFFSET        16                   
#define TDFI_CTRLUPD_MAX_WIDTH         14                   
#define TDFI_CTRLUPD_MIN_ADDR          25                   
#define TDFI_CTRLUPD_MIN_OFFSET        8                    
#define TDFI_CTRLUPD_MIN_WIDTH         4                    
#define TDFI_PHY_RDLAT_ADDR            25                   
#define TDFI_PHY_RDLAT_OFFSET          16                   
#define TDFI_PHY_RDLAT_WIDTH           4                    
#define TDFI_PHY_WRLAT_ADDR            25                   
#define TDFI_PHY_WRLAT_BASE_ADDR       26                   
#define TDFI_PHY_WRLAT_BASE_OFFSET     0                    
#define TDFI_PHY_WRLAT_BASE_WIDTH      4                    
#define TDFI_PHY_WRLAT_OFFSET          24                   
#define TDFI_PHY_WRLAT_WIDTH           4                    
#define TDFI_PHYUPD_RESP_ADDR          34                   
#define TDFI_PHYUPD_RESP_OFFSET        0                    
#define TDFI_PHYUPD_RESP_WIDTH         14                   
#define TDFI_PHYUPD_TYPE0_ADDR         34                   
#define TDFI_PHYUPD_TYPE0_OFFSET       16                   
#define TDFI_PHYUPD_TYPE0_WIDTH        14                   
#define TDFI_RDDATA_EN_ADDR            26                   
#define TDFI_RDDATA_EN_BASE_ADDR       26                   
#define TDFI_RDDATA_EN_BASE_OFFSET     16                   
#define TDFI_RDDATA_EN_BASE_WIDTH      4                    
#define TDFI_RDDATA_EN_OFFSET          8                    
#define TDFI_RDDATA_EN_WIDTH           4                    
#define TDLL_ADDR                      36                   
#define TDLL_OFFSET                    0                    
#define TDLL_WIDTH                     16                   
#define TFAW_ADDR                      28                   
#define TFAW_OFFSET                    8                    
#define TFAW_WIDTH                     5                    
#define TINIT_ADDR                     46                   
#define TINIT_OFFSET                   0                    
#define TINIT_WIDTH                    24                   
#define TMOD_ADDR                      185                  
#define TMOD_OFFSET                    8                    
#define TMOD_WIDTH                     8                    
#define TMRD_ADDR                      28                   
#define TMRD_OFFSET                    16                   
#define TMRD_WIDTH                     5                    
#define TPDEX_ADDR                     36                   
#define TPDEX_OFFSET                   16                   
#define TPDEX_WIDTH                    16                   
#define TRANS_COUNT_DLY_WIDTH          6                    
#define TRANS_COUNT_WIDTH              55                   
#define TRAS_LOCKOUT_ADDR              10                   
#define TRAS_LOCKOUT_OFFSET            0                    
#define TRAS_LOCKOUT_WIDTH             1                    
#define TRAS_MAX_ADDR                  37                   
#define TRAS_MAX_OFFSET                0                    
#define TRAS_MAX_WIDTH                 16                   
#define TRAS_MIN_ADDR                  30                   
#define TRAS_MIN_OFFSET                0                    
#define TRAS_MIN_WIDTH                 8                    
#define TRC_ADDR                       28                   
#define TRC_OFFSET                     24                   
#define TRC_WIDTH                      5                    
#define TRCD_INT_ADDR                  30                   
#define TRCD_INT_OFFSET                8                    
#define TRCD_INT_WIDTH                 8                    
#define TRCD_WIDTH                     8                    
#define TREF_ADDR                      35                   
#define TREF_ENABLE_ADDR               10                   
#define TREF_ENABLE_OFFSET             8                    
#define TREF_ENABLE_WIDTH              1                    
#define TREF_OFFSET                    0                    
#define TREF_WIDTH                     14                   
#define TRFC_ADDR                      30                   
#define TRFC_OFFSET                    16                   
#define TRFC_WIDTH                     8                    
#define TRP_ADDR                       26                   
#define TRP_OFFSET                     24                   
#define TRP_WIDTH                      4                    
#define TRRD_ADDR                      17                   
#define TRRD_OFFSET                    8                    
#define TRRD_WIDTH                     3                    
#define TRTP_ADDR                      17                   
#define TRTP_OFFSET                    16                   
#define TRTP_WIDTH                     3                    
#define TWR_INT_ADDR                   17                   
#define TWR_INT_OFFSET                 24                   
#define TWR_INT_WIDTH                  5                    
#define TWR_WIDTH                      5                    
#define TWTR_ADDR                      18                   
#define TWTR_OFFSET                    0                    
#define TWTR_WIDTH                     4                    
#define TXSNR_ADDR                     37                   
#define TXSNR_OFFSET                   16                   
#define TXSNR_WIDTH                    16                   
#define TXSR_ADDR                      38                   
#define TXSR_OFFSET                    0                    
#define TXSR_WIDTH                     16                   
#define TYPE_WIDTH                     3                    
#define UNALIGNED_ACCESS_ADDRESS_ADDR  189                  
#define UNALIGNED_ACCESS_ADDRESS_OFFSET 0                    
#define UNALIGNED_ACCESS_ADDRESS_WIDTH 36                   
#define UNALIGNED_ACCESS_LENGTH_ADDR   184                  
#define UNALIGNED_ACCESS_LENGTH_OFFSET 24                   
#define UNALIGNED_ACCESS_LENGTH_WIDTH  7                    
#define USER_BYTE_WIDTH                4                    
#define USER_DATA_WIDTH                128                  
#define USER_MASK_WIDTH                16                   
#define VERSION_ADDR                   38                   
#define VERSION_OFFSET                 16                   
#define VERSION_WIDTH                  16                   
#define W2R_DIFFCS_DLY_ADDR            183                  
#define W2R_DIFFCS_DLY_OFFSET          16                   
#define W2R_DIFFCS_DLY_WIDTH           3                    
#define W2R_HOLDOFF_DLY_WIDTH          6                    
#define W2R_HOLDOFF_SLICE_WIDTH        2                    
#define W2R_HOLDOFF_WIDTH              72                   
#define W2R_SAMECS_DLY_ADDR            183                  
#define W2R_SAMECS_DLY_OFFSET          24                   
#define W2R_SAMECS_DLY_WIDTH           3                    
#define WEIGHTED_ROUND_ROBIN_LATENCY_CONTROL_ADDR 10                   
#define WEIGHTED_ROUND_ROBIN_LATENCY_CONTROL_OFFSET 16                   
#define WEIGHTED_ROUND_ROBIN_LATENCY_CONTROL_WIDTH 1                    
#define WEIGHTED_ROUND_ROBIN_WEIGHT_SHARING_ADDR 10                   
#define WEIGHTED_ROUND_ROBIN_WEIGHT_SHARING_OFFSET 24                   
#define WEIGHTED_ROUND_ROBIN_WEIGHT_SHARING_WIDTH 1                    
#define WRCMD_LAT_WIDTH                4                    
#define WRDATA_LAT_WIDTH               4                    
#define WRITE_CNT_WIDTH                2                    
#define WRITE_FIFO_DEPTH_WIDTH         2                    
#define WRITE_FIFO_SRAM_DEPTH_WIDTH    3                    
#define WRITE_FIFO_STATUS_WIDTH        4                    
#define WRITE_MODEREG_ADDR             11                   
#define WRITE_MODEREG_OFFSET           8                    
#define WRITE_MODEREG_WIDTH            1                    
#define WRITEINTERP_ADDR               11                   
#define WRITEINTERP_OFFSET             0                    
#define WRITEINTERP_WIDTH              1                    
#define WRLAT_ADDR                     18                   
#define WRLAT_ADJ_ADDR                 184                  
#define WRLAT_ADJ_OFFSET               16                   
#define WRLAT_ADJ_WIDTH                4                    
#define WRLAT_OFFSET                   8                    
#define WRLAT_WIDTH                    4                    
#define WRR_PARAM_VALUE_ERR_ADDR       27                   
#define WRR_PARAM_VALUE_ERR_OFFSET     0                    
#define WRR_PARAM_VALUE_ERR_WIDTH      4                    
#define XOR_CHECK_BITS_ADDR            39                   
#define XOR_CHECK_BITS_OFFSET          0                    
#define XOR_CHECK_BITS_WIDTH           16                   
