#!/usr/bin/python
# NumaConnect checker r12

import os, time, optparse, operator, nclib

if os.getuid():
	raise SystemExit('error: please run as root')

parser = optparse.OptionParser()
parser.add_option('--once', dest='once', action='store_true', default=False, help='check once rather than periodically')
parser.add_option('--local', dest='local', action='store_true', default=False, help='check local registers only')
# required in nclib
parser.add_option('--verbose', dest='verbose', default=0, action='count', help='increase verbosity')
parser.add_option('--lean', dest='lean', action='store_true', default=False, help='check numachip registers only')

nclib.pin(0) # needed to ensure correct raw access
nclib.options, args = parser.parse_args()
nclib.platform = nclib.Platform()
nclib.numachip = nclib.Numachip()
nodes = []

try:
	for z in range(max(nclib.platform.oemn.size_z, 1)):
		for y in range(max(nclib.platform.oemn.size_y, 1)):
			for x in range(max(nclib.platform.oemn.size_x, 1)):
				nodes.append(nclib.Node(x | y << 4 | z << 8))

except nclib.Numachip.BlockedException:
	raise SystemError('error: fabric blocked; unable to determine geometry')

logf = open('nc-check.log', 'a')

try:
	while True:
		output = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())
		if nclib.options.verbose > 0:
			output += ' ['

		if nclib.options.verbose > 0:
			ptrs = {}
			total = 0
			for node in nodes:
				ptr = node.state()
				if ptr:
					try:
						ptrs[ptr] += 1
					except KeyError:
						ptrs[ptr] = 1
					total += 1

			for key, val in sorted(ptrs.items(), key=operator.itemgetter(1), reverse=True):
				output += '%2u%%@%03x' % (val * 100 / total, key),
			output += ']'

		errors = 0
		for node in nodes:
			errstr = node.check()
			if errstr:
				output += ' ' + errstr

		print output
		print >>logf, output

		if nclib.options.once:
			break

		time.sleep(3)
except nclib.Numachip.TimeoutException:
	raise SystemError('error: fabric timeout')
except nclib.Numachip.BlockedException:
	raise SystemError('error: fabric blocked')
except KeyboardInterrupt:
	pass
